debug: true
secret_key: 'JeFvgCrMuvkoAJjkHgyaMDxku'

pgx:
  dsn: postgres://postgres:postgres@localhost:5432/realworld_test?sslmode=disable

uptrace:
  dsn: https://<key>@api.uptrace.dev/<project_id>
